export enum ErrorMessageKey {
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  ACCOUNT_DISABLED = 'ACCOUNT_DISABLED',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_EXIST = 'USER_EXIST',
  USER_ALREADY_VERIFIED = 'USER_ALREADY_VERIFIED',
  INVALID_VERIFICATION_CODE = 'INVALID_VERIFICATION_CODE',
  VERIFICATION_CODE_EXPIRED = 'VERIFICATION_CODE_EXPIRED',
  PASSWORD_SAME_AS_OLD = 'PASSWORD_SAME_AS_OLD',

  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
