export enum ErrorMessageKey {
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  ACCOUNT_DISABLED = 'ACCOUNT_DISABLED',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_EXIST = 'USER_EXIST',
  USER_ALREADY_VERIFIED = 'USER_ALREADY_VERIFIED',
  PHONE_ALREADY_EXISTS = 'PHONE_ALREADY_EXISTS',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  INVALID_VERIFICATION_CODE = 'INVALID_VERIFICATION_CODE',
  VERIFICATION_CODE_EXPIRED = 'VERIFICATION_CODE_EXPIRED',
  PASSWORD_SAME_AS_OLD = 'PASSWORD_SAME_AS_OLD',

  DEPARTEMENT_EXIST = 'DEPARTEMENT_EXIST',

  CLASS_EXIST = 'CLASS_EXIST',
  CLASS_NOT_FOUND = 'CLASS_NOT_FOUND',

  STUDENT_EXIST = 'STUDENT_EXIST',
  STUDENT_NOT_FOUND = 'STUDENT_NOT_FOUND',

  EXCEL_EMPTY = 'EXCEL_EMPTY',

  COURSE_NOT_FOUND = 'COURSE_NOT_FOUND',

  VALIDATION_FAILED = 'VALIDATION_FAILED',

  TOPIC_EXIST = 'TOPIC_EXIST',
  TOPIC_NOT_FOUND = 'TOPIC_NOT_FOUND',

  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',

  // Shared generation
  GENERATION_AI_API_FAILED = 'GENERATION_AI_API_FAILED',
  GENERATION_AI_INVALID_JSON = 'GENERATION_AI_INVALID_JSON',
  GENERATION_EMPTY_RESULT = 'GENERATION_EMPTY_RESULT',
  GENERATION_JOB_NOT_FOUND = 'GENERATION_JOB_NOT_FOUND',
  GENERATION_JOB_FAILED = 'GENERATION_JOB_FAILED',
  GENERATION_NETWORK_ERROR = 'GENERATION_NETWORK_ERROR',
  GENERATION_TIMEOUT = 'GENERATION_TIMEOUT',
  GENERATION_QUEUE_UNAVAILABLE = 'GENERATION_QUEUE_UNAVAILABLE',

  // Assessment generation
  ASSESSMENT_SHELL_NOT_FOUND = 'ASSESSMENT_SHELL_NOT_FOUND',
  ASSESSMENT_AI_QUESTION_FAILED = 'ASSESSMENT_AI_QUESTION_FAILED',
  ASSESSMENT_AI_INVALID_QUESTIONS_PAYLOAD = 'ASSESSMENT_AI_INVALID_QUESTIONS_PAYLOAD',
  ASSESSMENT_GENERATE_FAILED = 'ASSESSMENT_GENERATE_FAILED',

  // Course extract
  COURSE_EXTRACT_FILE_REQUIRED = 'COURSE_EXTRACT_FILE_REQUIRED',
  COURSE_EXTRACT_UNSUPPORTED_FILE = 'COURSE_EXTRACT_UNSUPPORTED_FILE',
  COURSE_EXTRACT_EMPTY_DOCX = 'COURSE_EXTRACT_EMPTY_DOCX',
  COURSE_EXTRACT_INVALID_DOCX = 'COURSE_EXTRACT_INVALID_DOCX',
  COURSE_EXTRACT_AI_INVALID_RESPONSE = 'COURSE_EXTRACT_AI_INVALID_RESPONSE',
  COURSE_EXTRACT_FAILED = 'COURSE_EXTRACT_FAILED',
  COURSE_EXTRACT_START_FAILED = 'COURSE_EXTRACT_START_FAILED',

  // Topic content
  TOPIC_CONTENT_LECTURE_REQUIRED = 'TOPIC_CONTENT_LECTURE_REQUIRED',
  TOPIC_CONTENT_GENERATE_FAILED = 'TOPIC_CONTENT_GENERATE_FAILED',
  TOPIC_CONTENT_LECTURE_FAILED = 'TOPIC_CONTENT_LECTURE_FAILED',
  TOPIC_CONTENT_SLIDES_FAILED = 'TOPIC_CONTENT_SLIDES_FAILED',
  TOPIC_CONTENT_LAB_FAILED = 'TOPIC_CONTENT_LAB_FAILED',
  TOPIC_CONTENT_EMPTY_RESULT = 'TOPIC_CONTENT_EMPTY_RESULT',
  TOPIC_CONTENT_UNSUPPORTED_TYPE = 'TOPIC_CONTENT_UNSUPPORTED_TYPE',
  TOPIC_CONTENT_FILE_REQUIRED = 'TOPIC_CONTENT_FILE_REQUIRED',
  TOPIC_CONTENT_GENERATION_CANCELLED = 'TOPIC_CONTENT_GENERATION_CANCELLED',

  // Skywork PPT
  SKYWORK_API_KEY_MISSING = 'SKYWORK_API_KEY_MISSING',
  SKYWORK_PPT_GENERATION_FAILED = 'SKYWORK_PPT_GENERATION_FAILED',
  SKYWORK_PPT_NO_DOWNLOAD_URL = 'SKYWORK_PPT_NO_DOWNLOAD_URL',
  SKYWORK_PPT_DOWNLOAD_FAILED = 'SKYWORK_PPT_DOWNLOAD_FAILED',
  SKYWORK_PPT_INSUFFICIENT_BENEFIT = 'SKYWORK_PPT_INSUFFICIENT_BENEFIT',
  SKYWORK_PPT_BILLING_ERROR = 'SKYWORK_PPT_BILLING_ERROR',
}
