export enum ErrorMessageKey {
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  ACCOUNT_DISABLED = 'ACCOUNT_DISABLED',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_EXIST = 'USER_EXIST',
  USER_ALREADY_VERIFIED = 'USER_ALREADY_VERIFIED',
  PHONE_ALREADY_EXISTS = 'PHONE_ALREADY_EXISTS',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  INVALID_VERIFICATION_CODE = 'INVALID_VERIFICATION_CODE',
  VERIFICATION_CODE_EXPIRED = 'VERIFICATION_CODE_EXPIRED',
  PASSWORD_SAME_AS_OLD = 'PASSWORD_SAME_AS_OLD',

  DEPARTEMENT_EXIST = 'DEPARTEMENT_EXIST',

  CLASS_EXIST = 'CLASS_EXIST',
  CLASS_NOT_FOUND = 'CLASS_NOT_FOUND',

  STUDENT_EXIST = 'STUDENT_EXIST',
  STUDENT_NOT_FOUND = 'STUDENT_NOT_FOUND',

  EXCEL_EMPTY = 'EXCEL_EMPTY',

  COURSE_NOT_FOUND = 'COURSE_NOT_FOUND',

  VALIDATION_FAILED = 'VALIDATION_FAILED',

  TOPIC_EXIST = 'TOPIC_EXIST',
  TOPIC_NOT_FOUND = 'TOPIC_NOT_FOUND',

  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
