export enum ResponseMessageKey {
  REGISTER_SUCCESS = 'REGISTER_SUCCESS',
  VERIFICATION_CODE_SENT = 'VERIFICATION_CODE_SENT',
  CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS',
  USER_ACCOUNT_VERIFIED_SUCCESS = 'USER_ACCOUNT_VERIFIED_SUCCESS',
  USER_UPDATED_SUCCESS = 'USER_UPDATED_SUCCESS',
}
