/** Stable validation keys returned by Zod schemas — translate on the frontend. */
export const ValidationMessageKey = {
  // Auth
  EMAIL_REQUIRED: 'EMAIL_REQUIRED',
  EMAIL_INVALID: 'EMAIL_INVALID',
  PASSWORD_REQUIRED: 'PASSWORD_REQUIRED',
  PASSWORD_MIN_LENGTH: 'PASSWORD_MIN_LENGTH',
  PASSWORD_COMPLEXITY: 'PASSWORD_COMPLEXITY',
  PHONE_INVALID: 'PHONE_INVALID',
  FIRST_NAME_MIN_LENGTH: 'FIRST_NAME_MIN_LENGTH',
  LAST_NAME_MIN_LENGTH: 'LAST_NAME_MIN_LENGTH',

  // Course
  TITLE_REQUIRED: 'TITLE_REQUIRED',
  TEACHING_MODE_INVALID: 'TEACHING_MODE_INVALID',
  CREDIT_HOURS_INVALID: 'CREDIT_HOURS_INVALID',
  PASS_RATE_INVALID: 'PASS_RATE_INVALID',

  // CLO
  CLO_CODE_REQUIRED: 'CLO_CODE_REQUIRED',
  CLO_DESCRIPTION_REQUIRED: 'CLO_DESCRIPTION_REQUIRED',

  // Topic
  TOPIC_NUMBER_INVALID: 'TOPIC_NUMBER_INVALID',
  TOPIC_TITLE_REQUIRED: 'TOPIC_TITLE_REQUIRED',
  CONTACT_HOURS_INVALID: 'CONTACT_HOURS_INVALID',

  // Reference
  REFERENCE_TYPE_INVALID: 'REFERENCE_TYPE_INVALID',
  REFERENCE_TITLE_REQUIRED: 'REFERENCE_TITLE_REQUIRED',

  // Assessment
  ASSESSMENT_TITLE_REQUIRED: 'ASSESSMENT_TITLE_REQUIRED',
  ASSESSMENT_TYPE_INVALID: 'ASSESSMENT_TYPE_INVALID',
  ASSESSMENT_DURATION_INVALID: 'ASSESSMENT_DURATION_INVALID',
  ASSESSMENT_TOTAL_MARKS_INVALID: 'ASSESSMENT_TOTAL_MARKS_INVALID',
  ASSESSMENT_PASS_MARK_INVALID: 'ASSESSMENT_PASS_MARK_INVALID',
  ASSESSMENT_PASS_MARK_RANGE: 'ASSESSMENT_PASS_MARK_RANGE',
  ASSESSMENT_PASS_MARK_EXCEEDS_TOTAL: 'ASSESSMENT_PASS_MARK_EXCEEDS_TOTAL',
  ASSESSMENT_VERSIONS_INVALID: 'ASSESSMENT_VERSIONS_INVALID',
  ASSESSMENT_STUDENT_ID_DIGITS_INVALID: 'ASSESSMENT_STUDENT_ID_DIGITS_INVALID',
  ASSESSMENT_DIFFICULTY_INVALID: 'ASSESSMENT_DIFFICULTY_INVALID',
  ASSESSMENT_LANGUAGE_INVALID: 'ASSESSMENT_LANGUAGE_INVALID',
  INVALID_ENUM_VALUE: 'INVALID_ENUM_VALUE',
} as const;

export type ValidationMessageKey =
  (typeof ValidationMessageKey)[keyof typeof ValidationMessageKey];
